name: qcabs_driver
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+7

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_bloc: ^7.0.0
  shared_preferences: ^2.0.5
#  charts_flutter: ^0.10.0
  solid_bottom_sheet:
    git:
      url: https://github.com/dbenitez-bcn/solid_bottom_sheet.git

  animation_wrappers: ^0.0.4
  google_maps_flutter: ^2.0.6
  flutter_polyline_points: ^1.0.0
  #  google_mobile_ads: ^0.13.2
  equatable: ^2.0.3
  flutter_native_splash: ^1.3.2
  flutter_spinkit: ^5.1.0
  badges: ^2.0.2
  im_stepper: ^0.1.3
  modal_bottom_sheet: ^2.0.1
  dropdown_search: ^2.0.1
  floating_action_bubble: ^1.1.4
  date_time_picker: ^2.1.0
  dropdown_button2: ^1.4.0
  rflutter_alert: ^2.0.4
  expandable: ^5.0.1
  flutter_appauth: ^2.4.1
  http: ^0.13.4
  aad_oauth: ^0.3.0
  flutter_easyloading: ^3.0.3
  dio: ^4.0.6
  geolocator: ^8.0.5
  geolocator_android: 3.1.5
  shimmer: ^2.0.0
  toast: ^0.3.0
  blinking_text: ^1.0.2
  sqflite: ^2.0.2
  google_fonts: ^2.3.0
  intl: ^0.17.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_icon.png"

flutter_launcher_name:
  name: "Atlantix cargo+"

flutter:

  uses-material-design: true

  assets:
    - assets/